import type { Metadata } from "next";
import "../globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Random Quotes",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin = cookies().get('Authorization')?.value;
  if (!isLogin || isLogin.length <= 0) {
    redirect ('/');
  }
  return (
    <html lang="en">
      <body>
        <div className="bg-white h-screen">
        <NavbarComponent />
        {children}
        </div>
        </body>
    </html>
  );
}
