import type { Metadata } from "next";
import "../globals.css";
import NavbarComponent from "@/components/NavbarComponent";

export const metadata: Metadata = {
  title: "Random Quotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-white h-screen">
        <NavbarComponent />
        {children}
        </div>
        </body>
    </html>
  );
}
