import type { Metadata } from "next";
import "./globals.css";
import { CookiesProvider } from 'next-client-cookies/server';


export const metadata: Metadata = {
  title: "Random Quotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CookiesProvider>
          {children}
        </CookiesProvider>
      </body>
    </html>
  );
}
